import { makeReqType, makeResType } from '../../utils/makeType';

export const START_APPLICATION = makeReqType('START_APPLICATION');
export const START_APPLICATION_RES = makeResType('START_APPLICATION_RES');

export const APPLICATION_GET_CURRENT = makeReqType('APPLICATION_GET_CURRENT');
export const APPLICATION_GET_CURRENT_RES = makeResType('APPLICATION_GET_CURRENT_RES');

export const APPLICATION_GET_WINDOW = makeReqType('APPLICATION_GET_WINDOW');
export const APPLICATION_GET_WINDOW_RES = makeResType('APPLICATION_GET_WINDOW_RES');

export const APPLICATION_WRAP = makeReqType('APPLICATION_WRAP');
export const APPLICATION_WRAP_RES = makeResType('APPLICATION_WRAP_RES');

export const APPLICATION_ADD_LISTENER = makeReqType('APPLICATION_ADD_LISTENER');
export const APPLICATION_ADD_LISTENER_RES = makeResType('APPLICATION_ADD_LISTENER_RES');

export const APPLICATION_QUIT = makeReqType('APPLICATION_QUIT');
export const APPLICATION_QUIT_RES = makeResType('APPLICATION_QUIT_RES');

export const APPLICATION_GET_CHILD_WINDOWS = makeReqType('APPLICATION_GET_CHILD_WINDOWS');
export const APPLICATION_GET_CHILD_WINDOWS_RES = makeResType('APPLICATION_GET_CHILD_WINDOWS_RES');

export const APPLICATION_GET_INFO = makeReqType('APPLICATION_GET_INFO');
export const APPLICATION_GET_INFO_RES = makeResType('APPLICATION_GET_INFO_RES');

export const APPLICATION_GET_SHORTCUTS = makeReqType('APPLICATION_GET_SHORTCUTS');
export const APPLICATION_GET_SHORTCUTS_RES = makeResType('APPLICATION_GET_SHORTCUTS_RES');

export const APPLICATION_GET_TRAY_ICON_INFO = makeReqType('APPLICATION_GET_TRAY_ICON_INFO');
export const APPLICATION_GET_TRAY_ICON_INFO_RES = makeResType('APPLICATION_GET_TRAY_ICON_INFO_RES');

export const APPLICATION_GET_ZOOM_LEVEL = makeReqType('APPLICATION_GET_ZOOM_LEVEL');
export const APPLICATION_GET_ZOOM_LEVEL_RES = makeResType('APPLICATION_GET_ZOOM_LEVEL_RES');

export const APPLICATION_IS_RUNNING = makeReqType('APPLICATION_IS_RUNNING');
export const APPLICATION_IS_RUNNING_RES = makeResType('APPLICATION_IS_RUNNING_RES');

export const APPLICATION_REMOVE_LISTENER = makeReqType('APPLICATION_REMOVE_LISTENER');
export const APPLICATION_REMOVE_LISTENER_RES = makeResType('APPLICATION_REMOVE_LISTENER_RES');

export const RESTART = makeReqType('APPLICATION_RESTART');
export const RESTART_RES = makeResType('APPLICATION_RESTART_RES');

export const APPLICATION_SCHEDULE_RESTART = makeReqType('APPLICATION_SCHEDULE_RESTART');
export const APPLICATION_SCHEDULE_RESTART_RES = makeResType('APPLICATION_SCHEDULE_RESTART_RES');

export const APPLICATION_SET_SHORTCUTS = makeReqType('APPLICATION_SET_SHORTCUTS');
export const APPLICATION_SET_SHORTCUTS_RES = makeResType('APPLICATION_SET_SHORTCUTS_RES');

export const APPLICATION_SET_TRAY_ICON = makeReqType('APPLICATION_SET_TRAY_ICON');
export const APPLICATION_SET_TRAY_ICON_RES = makeResType('APPLICATION_SET_TRAY_ICON_RES');

export const APPLICATION_SET_ZOOM_LEVEL = makeReqType('APPLICATION_SET_ZOOM_LEVEL');
export const APPLICATION_SET_ZOOM_LEVEL_RES = makeResType('APPLICATION_SET_ZOOM_LEVEL_RES');

export const APPLICATION_TERMINATE = makeReqType('APPLICATION_TERMINATE');
export const APPLICATION_TERMINATE_RES = makeResType('APPLICATION_TERMINATE_RES');
