import makeType from '../../utils/makeType';

export const NEW_APPLICATION = makeType('NEW_APPLICATION');
export const NEW_APPLICATION_RES = makeType('NEW_APPLICATION_RES');

export const APPLICATION_GET_CURRENT = makeType('APPLICATION_GET_CURRENT');
export const APPLICATION_GET_CURRENT_RES = makeType('APPLICATION_GET_CURRENT_RES');

export const APPLICATION_GET_WINDOW = makeType('APPLICATION_GET_WINDOW');
export const APPLICATION_GET_WINDOW_RES = makeType('APPLICATION_GET_WINDOW_RES');

export const APPLICATION_WRAP = makeType('APPLICATION_WRAP');
export const APPLICATION_WRAP_RES = makeType('APPLICATION_WRAP_RES');

export const APPLICATION_ADD_EVENT_LISTENER = makeType('APPLICATION_ADD_EVENT_LISTENER');
export const APPLICATION_ADD_EVENT_LISTENER_RES = makeType('APPLICATION_ADD_EVENT_LISTENER_RES');

export const CLOSE = makeType('APPLICATION_CLOSE');
export const CLOSE_RES = makeType('APPLICATION_CLOSE_RES');

export const APPLICATION_GET_CHILD = makeType('APPLICATION_GET_CHILD');
export const APPLICATION_GET_CHILD_RES = makeType('APPLICATION_GET_CHILD_RES');

export const APPLICATION_GET_INFO = makeType('APPLICATION_GET_INFO');
export const APPLICATION_GET_INFO_RES = makeType('APPLICATION_GET_INFO_RES');

export const APPLICATION_GET_SHORTCUTS = makeType('APPLICATION_GET_SHORTCUTS');
export const APPLICATION_GET_SHORTCUTS_RES = makeType('APPLICATION_GET_SHORTCUTS_RES');

export const APPLICATION_GET_TRAY_ICON_INFO = makeType('APPLICATION_GET_TRAY_ICON_INFO');
export const APPLICATION_GET_TRAY_ICON_INFO_RES = makeType('APPLICATION_GET_TRAY_ICON_INFO_RES');

export const APPLICATION_GET_ZOOM_LEVEL = makeType('APPLICATION_GET_ZOOM_LEVEL');
export const APPLICATION_GET_ZOOM_LEVEL_RES = makeType('APPLICATION_GET_ZOOM_LEVEL_RES');

export const APPLICATION_IS_RUNNING = makeType('APPLICATION_IS_RUNNING');
export const APPLICATION_IS_RUNNING_RES = makeType('APPLICATION_IS_RUNNING_RES');

export const APPLICATION_REMOVE_EVENT_LISTENER = makeType('APPLICATION_REMOVE_EVENT_LISTENER');
export const APPLICATION_REMOVE_EVENT_LISTENER_RES = makeType('APPLICATION_REMOVE_EVENT_LISTENER_RES');

export const RESTART = makeType('APPLICATION_RESTART');
export const RESTART_RES = makeType('APPLICATION_RESTART_RES');

export const APPLICATION_SCHEDULE_RESTART = makeType('APPLICATION_SCHEDULE_RESTART');
export const APPLICATION_SCHEDULE_RESTART_RES = makeType('APPLICATION_SCHEDULE_RESTART_RES');

export const APPLICATION_SET_SHORTCUTS = makeType('APPLICATION_SET_SHORTCUTS');
export const APPLICATION_SET_SHORTCUTS_RES = makeType('APPLICATION_SET_SHORTCUTS_RES');

export const APPLICATION_SET_TRAY_ICON = makeType('APPLICATION_SET_TRAY_ICON');
export const APPLICATION_SET_TRAY_ICON_RES = makeType('APPLICATION_SET_TRAY_ICON_RES');

export const APPLICATION_SET_ZOOM_LEVEL = makeType('APPLICATION_SET_ZOOM_LEVEL');
export const APPLICATION_SET_ZOOM_LEVEL_RES = makeType('APPLICATION_SET_ZOOM_LEVEL_RES');

export const APPLICATION_TERMINATE = makeType('APPLICATION_TERMINATE');
export const APPLICATION_TERMINATE_RES = makeType('APPLICATION_TERMINATE_RES');
