import makeType from '../../utils/makeType';

export const CREATE_NOTIFICATION = makeType('CREATE_NOTIFICATION');
export const CREATE_NOTIFICATION_RES = makeType('CREATE_NOTIFICATION_RES');

export const NOTIFICATION_GET_CURRENT= makeType('NOTIFICATION_GET_CURRENT');
export const NOTIFICATION_GET_CURRENT_RES= makeType('NOTIFICATION_GET_CURRENT_RES');

export const NOTIFICATION_CLOSE= makeType('NOTIFICATION_CLOSE');
export const NOTIFICATION_CLOSE_RES= makeType('NOTIFICATION_CLOSE_RES');

export const NOTIFICATION_SEND_MSG= makeType('NOTIFICATION_SEND_MSG');
export const NOTIFICATION_SEND_MSG_RES= makeType('NOTIFICATION_SEND_MSG_RES');

export const NOTIFICATION_SEND_MSG_TO_APP= makeType('NOTIFICATION_SEND_MSG_TO_APP');
export const NOTIFICATION_SEND_MSG_TO_APP_RES= makeType('NOTIFICATION_SEND_MSG_TO_APP_RES');


// notification events
export const NOTIFICATION_ON_CLICK_RES      = makeType('NOTIFICATION_ON_CLICK_RES');
export const NOTIFICATION_ON_CLOSE_RES      = makeType('NOTIFICATION_ON_CLOSE_RES');
export const NOTIFICATION_ON_DISMISS_RES    = makeType('NOTIFICATION_ON_DISMISS_RES');
export const NOTIFICATION_ON_ERROR_RES      = makeType('NOTIFICATION_ON_ERROR_RES');
export const NOTIFICATION_ON_MSG_RES        = makeType('NOTIFICATION_ON_MSG_RES');
export const NOTIFICATION_ON_SHOW_RES       = makeType('NOTIFICATION_ON_SHOW_RES');
