import { makeReqType, makeResType } from '../../utils/makeType';

export const CREATE_NOTIFICATION = makeReqType('CREATE_NOTIFICATION');
export const CREATE_NOTIFICATION_RES = makeResType('CREATE_NOTIFICATION_RES');

export const NOTIFICATION_GET_CURRENT= makeReqType('NOTIFICATION_GET_CURRENT');
export const NOTIFICATION_GET_CURRENT_RES= makeResType('NOTIFICATION_GET_CURRENT_RES');

export const NOTIFICATION_CLOSE= makeReqType('NOTIFICATION_CLOSE');
export const NOTIFICATION_CLOSE_RES= makeResType('NOTIFICATION_CLOSE_RES');

export const NOTIFICATION_SEND_MSG= makeReqType('NOTIFICATION_SEND_MSG');
export const NOTIFICATION_SEND_MSG_RES= makeResType('NOTIFICATION_SEND_MSG_RES');

export const NOTIFICATION_SEND_MSG_TO_APP= makeReqType('NOTIFICATION_SEND_MSG_TO_APP');
export const NOTIFICATION_SEND_MSG_TO_APP_RES= makeResType('NOTIFICATION_SEND_MSG_TO_APP_RES');


// notification events
export const NOTIFICATION_ON_CLICK_RES      = makeResType('NOTIFICATION_ON_CLICK_RES');
export const NOTIFICATION_ON_CLOSE_RES      = makeResType('NOTIFICATION_ON_CLOSE_RES');
export const NOTIFICATION_ON_DISMISS_RES    = makeResType('NOTIFICATION_ON_DISMISS_RES');
export const NOTIFICATION_ON_ERROR_RES      = makeResType('NOTIFICATION_ON_ERROR_RES');
export const NOTIFICATION_ON_MSG_RES        = makeResType('NOTIFICATION_ON_MSG_RES');
export const NOTIFICATION_ON_SHOW_RES       = makeResType('NOTIFICATION_ON_SHOW_RES');
